name: OwnPremiumCase
main: me.symi.owncase.Main
author: Symi
version: 1.5
api-version: 1.15
website: https://owncraft.eu

commands:
  case:
    aliases: [ownpremiumcase,owncase]
    description: Create premium case command
  key:
    aliases: [ownkey]
    description: Get case key command
  setcase:
    description: Set case location command

permissions:
  ownpremiumcase.setcase:
    description: Setcase command permission
    default: op
  ownpremiumcase.key:
    description: Get key command permission
    default: op
  ownpremiumcase.case:
    description: Create case command permission
    default: op