name: OwnPremiumCase
main: me.symi.owncase.Main
author: Symi
version: 1.4
api-version: 1.15
website: https://owncraft.eu

commands:
  key:
    aliases: [ownpremiumcase,opc]
    description: Get case key command
  setcase:
    description: Set case location command

permissions:
  ownpremiumcase.setcase:
    description: Setcase command permission
    default: op
  ownpremiumcase.key:
    description: Get key command permission
    default: op